"""empty message

Revision ID: aaa17d559888
Revises: 0ec5bcc971de
Create Date: 2020-04-06 04:59:06.356467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa17d559888'
down_revision = '0ec5bcc971de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artists', sa.Column('seeking', sa.Boolean(), nullable=False))
    op.add_column('Artists', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Artists', sa.Column('site_link', sa.String(length=120), nullable=True))
    op.add_column('Venues', sa.Column('genres', sa.String(length=300), nullable=True))
    op.add_column('Venues', sa.Column('seeking', sa.Boolean(), nullable=False))
    op.add_column('Venues', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Venues', sa.Column('site_link', sa.String(length=120), nullable=True))
    op.alter_column('Venues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Venues', 'site_link')
    op.drop_column('Venues', 'seeking_description')
    op.drop_column('Venues', 'seeking')
    op.drop_column('Venues', 'genres')
    op.drop_column('Artists', 'site_link')
    op.drop_column('Artists', 'seeking_description')
    op.drop_column('Artists', 'seeking')
    op.drop_table('Shows')
    # ### end Alembic commands ###
